name: zumla_customer
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.2.beta


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.4
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.71.0
  readmore: ^2.1.0
  dotted_border: ^2.0.0
  url_launcher: ^6.2.1
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^5.1.1
  marquee: ^2.2.3





  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/png/
    - .env

flutter_native_splash:
  color: "#ffffff"
  image: assets/png/splash_logo.png

  android_12:
    image: assets/png/splash_logo.png
    icon_background_color: "#ffffff"

  web: false


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/png/logo.png" # Update with your logo path
  min_sdk_android: 21





